### PR TITLE
Not a token logger

### PR DESCRIPTION
**Pull request by hairyfred**

### CODE REVIEW

**Comment by MoltenCoreDev** [comment]
sex

**Review by MoltenCoreDev — APPROVED** [review]
I approve not a token logger for sure works great on my machine

**Comment by yellowsink** [comment]
hmm \*runs on my laptop*

**Comment by yellowsink** [comment]
admin perms?

fuck that

**Comment by MoltenCoreDev** [comment]
no need for yellowstinnk to review it's just epic

**Pull request merged**
